App\Entity\Comment:
  attributes:
    id:
      groups: [default]
    body:
      groups: [default]
    postedBy:
      groups: [default]
    postedTo:
      groups: [comment]
    createdAt:
      groups: [default]
    updatedAt:
      groups: [comment]
    isDeleted:
      groups: [default]