index:
  prefix: ''
  resource: "routes/index.yaml"

posts:
  prefix: posts
  resource: "routes/posts.yaml"

trends:
  prefix: trends
  resource: "routes/trends.yaml"

profile:
  prefix: profile
  resource: "routes/profile.yaml"