fos_rest:
    exception:
        exception_controller: 'fos_rest.exception.controller:showAction'
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violationList
