framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: app.session.handler
        cookie_secure: auto
        cookie_samesite: lax

    serializer:
        enabled: true
        mapping:
            paths:
                - "%kernel.project_dir%/src/Resources/config/serialization/"

    php_errors:
        log: true

    templating:
        engines: ['twig', 'php']

    http_method_override: true
