version: '3.3'

networks:
  nginx: ~
  mysql: ~
  cache: ~

volumes:
  db-data: ~

services:
  php-fpm:
    #image: TODO: Add image name
    restart: always
    expose:
      - 9000
    networks:
      - nginx
      - mysql
      - cache
    environment:
      DATABASE_NAME: dplanet
      DATABASE_USER: dplanet
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # TODO: Persist logs with a volume
  nginx:
    #image: TODO: Add image name
    restart: always
    ports:
      - 80:8080
      - 443:8443
    environment:
      fastcgi_cache_valid: 60m
      server_name: localhost
      hsts_max_time: 360000000
      cache_max_age: 60m
    networks:
      - nginx

  # TODO: Ensure Redis is secure with username/password
  redis:
    image: redis:5.0.5-alpine
    restart: always
    networks:
      - cache
    expose:
      - 6379