version: '3.3'

volumes:
  development_ssl: ~

services:
  php-fpm:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ../backend:/app/src:cached
      - ./php-fpm/bin/docker-entrypoint:/bin/docker-entrypoint:cached
      - development_ssl:/ssl
    networks:
      - mysql
    environment:
      DATABASE_PASSWORD: development
      CORS_ALLOW_ORIGIN: localhost
      REDIS_PASSWORD: developmentredispassword
      JWT_PASSPHRASE: 'developmentsecret'
      APP_ENV: dev
      JWT_SECRET: '/ssl/privkey.pem'
      JWT_PUBLIC: '/ssl/fullchain.pem'
      APP_DEBUG: "true"
      APP_SECRET: thisisasampletokenthatiputhereonlyfordevelopmentproductionhasasecretsecretofcourse

  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    networks:
      - mysql
      - nginx
    environment:
      PMA_HOST: mysql
    ports:
      - 8000:80

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    environment:
      server_name: localhost
      hsts_max_time: 0m
      fastcgi_cache_valid: 1s
      cache_max_age: 1
      default_action: 'proxy_pass http://node:3000'
    volumes:
      - development_ssl:/etc/letsencrypt/live/localhost
      - ../backend/public/uploads:/var/www/html/uploads:cached
      - ../backend/public/bundles:/var/www/html/bundles:cached
      - ./nginx/etc/nginx/temp:/etc/nginx/temp:cached

  mysql:
    environment:
      MYSQL_PASSWORD: development
      MYSQL_ROOT_PASSWORD: developmentroot
    ports:
      - 3306:3306

  redis:
    build:
      context: ../
      dockerfile: docker/redis/Dockerfile
    environment:
      REDIS_PASSWORD: developmentredispassword

  node:
    image: node:12.8.1-alpine
    user: node
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - nginx
    volumes:
      - ../frontend:/app
    working_dir: /app
    environment:
      NODE_ENV: dev
    command: ["/bin/sh", "-c", "yarn install && npm start"]
