version: '3.3'

volumes:
  development_ssl: ~

networks:
  mysql: ~

services:
  php-fpm:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ../src:/app/src:cached
      - ./php-fpm/bin/docker-entrypoint:/bin/docker-entrypoint:cached
    networks:
      - mysql
    environment:
      DATABASE_PASSWORD: development
      CORS_ALLOW_ORIGIN: localhost
      REDIS_PASSWORD: developmentredispassword
      APP_ENV: dev
      APP_DEBUG: "true"
      APP_SECRET: thisisasampletokenthatiputhereonlyfordevelopmentproductionhasasecretsecretofcourse

  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl

  webpack:
    image: node:12.8.0-alpine
    user: node
    volumes:
      - ../src:/app:cached
    ports:
      - 8080:8080
    working_dir: /app
    restart: always
    command: ["/bin/sh", "-c", "yarn install && npm rebuild node-sass && yarn watch"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - mysql
      - nginx
    environment:
      PMA_HOST: mysql
    ports:
      - 8000:80

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    environment:
      server_name: localhost
      hsts_max_time: 0m
      fastcgi_cache_valid: 1s
      cache_max_age: 1
    volumes:
      - development_ssl:/etc/letsencrypt/live/localhost
      - ../src/public:/var/www/html:cached
      - ./nginx/etc/nginx/temp:/etc/nginx/temp:cached

  mysql:
    build:
      context: ../
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_PASSWORD: development
    ports:
      - 3306:3306

  redis:
    build:
      context: ../
      dockerfile: docker/redis/Dockerfile
    environment:
      REDIS_PASSWORD: developmentredispassword
