version: '3.3'

networks:
  nginx: ~
  cache: ~
  mysql: ~

volumes:
  db-data: ~
  log: ~

services:
  php-fpm:
    image: dplanet/php-fpm:latest
    restart: always
    expose:
      - 9000
    networks:
      - nginx
      - cache
      - mysql
    environment:
      DATABASE_HOSTNAME: mysql
      DATABASE_NAME: dplanet
      DATABASE_USER: dplanet
      REDIS_HOST: redis
      REDIS_PORT: 6379

  nginx:
    image: dplanet/nginx:latest
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - log:/var/log/nginx
    networks:
      - nginx

  redis:
    image: dplanet/redis:latest
    restart: always
    networks:
      - cache
    expose:
      - 6379

  # TODO: Add a dedicated database later instead of using a container
  mysql:
    image: mysql:5.7
    networks:
      - mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: dplanet
      MYSQL_USER: dplanet
