version: '3.3'

volumes:
  development_ssl: ~

services:
  php-fpm:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ../src:/app/src:cached
      - ./php-fpm/bin/docker-entrypoint:/bin/docker-entrypoint:cached
    environment:
      DATABASE_HOSTNAME: mysql
      DATABASE_PASSWORD: development
      APP_ENV: dev
      APP_DEBUG: "true"
      APP_SECRET: thisisasampletokenthatiputhereonlyfordevelopmentproductionhasasecretsecretofcourse

  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    environment:
      server_name: localhost
      hsts_max_time: 0m
      fastcgi_cache_valid: 1s
      cache_max_age: 1
    volumes:
      - development_ssl:/etc/letsencrypt/live/localhost
      - ../src/public/assets:/var/www/html/assets:cached
      - ./nginx/etc/nginx/temp:/etc/nginx/temp:cached

  mysql:
    image: mysql:5.7
    networks:
      - mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: dplanet
      MYSQL_USER: dplanet
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_PASSWORD: development
    ports:
      - 3306:3306
