version: '3.3'

volumes:
  uploads: ~
  bundles: ~

services:
  nginx:
    image: dplanet/nginx:${docker_tag}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - uploads:/var/www/html/uploads
      - bundles:/var/www/html/bundles
    environment:
      server_name: ${server_name}
      hsts_max_time: 30000000
      cache_max_time: 120m
      fastcgi_cache_valid: 1m

  php-fpm:
    image: dplanet/php-fpm:${docker_tag}
    environment:
      CORS_ALLOW_ORIGIN: thedeveloperplanet.com
      APP_ENV: prod
      APP_DEBUG: "false"
      DATABASE_PASSWORD: <<DOCKER-SECRET:DB_PASSWORD>>
      REDIS_PASSWORD: <<DOCKER-SECRET:REDIS_PASSWORD>>
    volumes:
      - uploads:/app/public/uploads
      - bundles:/app/public/bundles
    secrets:
      - DB_PASSWORD
      - REDIS_PASSWORD

  mysql:
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/DB_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/DB_ROOT_PASSWORD
    ports:
      - 127.0.0.1:6612:3306 # For SSH tunnels
    secrets:
      - DB_PASSWORD
      - DB_ROOT_PASSWORD

  redis:
    image: dplanet/redis:${docker_tag}
    environment:
      REDIS_PASSWORD: <<DOCKER-SECRET:REDIS_PASSWORD>>
    secrets:
      - REDIS_PASSWORD

secrets:
  DB_PASSWORD:
    file: ${secrets_folder}/DB_PASSWORD
  REDIS_PASSWORD:
    file: ${secrets_folder}/REDIS_PASSWORD
  DB_ROOT_PASSWORD:
    file: ${secrets_folder}/DB_ROOT_PASSWORD
