doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        host: '%env(resolve:DATABASE_HOSTNAME)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                second_level_cache:
                    enabled: true
                metadata_cache_driver:
                    type: predis
                    host: "%env(REDIS_HOST)%"
                query_cache_driver:
                    type: predis
                    host: "%env(REDIS_HOST)%"
                result_cache_driver:
                    type: predis
                    host: "%env(REDIS_HOST)%"
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/src/Resources/config/doctrine'
                        prefix: 'App\Entity'
