---
- name: "Build images with tag {{ docker_tag }}"
  docker_image:
    source: build
    build:
      dockerfile: "{{ item.dockerfile }}"
      path: "{{ item.path }}"
      pull: false
      buildargs: "{{ item.buildargs | default(omit) }}"
    name: "{{ item.name }}"
    tag: "{{ docker_tag }}"
  with_items: "{{ docker_images }}"

- name: "Add latest tag to built images"
  docker_image:
    source: pull
    build:
      pull: no
    name: "{{ item.name }}:{{ docker_tag }}"
    repository: "{{ item.name }}:latest"
  with_items: "{{ docker_images }}"
  when: add_latest_tag|bool
