posts:
  prefix: posts
  resource: "routes/posts.yaml"

trends:
  prefix: trends
  resource: "routes/trends.yaml"

comments:
  prefix: comments
  resource: "routes/comments.yaml"

developer:
  prefix: developers
  resource: "routes/developers.yaml"
