comments.list:
  path: /
  controller: App\Action\Comment\Index
  methods: [GET]

comments.show:
  path: /{comment}
  controller: App\Action\Comment\Show
  methods: [GET]

comments.edit:
  path: /{comment}
  controller: App\Action\Comment\Edit
  methods: [PUT]

comments.delete:
  path: /{comment}
  controller: App\Action\Comment\Delete
  methods: [DELETE]
