comments.list:
  path: /
  controller: App\Controller\CommentController::list
  methods: [GET]

comments.show:
  path: /{comment}
  controller: App\Controller\CommentController::show
  methods: [GET]

comments.edit:
  path: /{comment}
  controller: App\Controller\CommentController::edit
  methods: [PATCH]

comments.delete:
  path: /{comment}
  controller: App\Controller\CommentController::delete
  methods: [DELETE]
