developers.index:
  path: /
  controller: App\Controller\DeveloperController::index
  methods: [GET]

developers.create:
  path: /
  controller: App\Controller\DeveloperController::create
  methods: [POST]

developers.show:
  path: /{developer}
  controller: App\Controller\DeveloperController::show
  methods: [GET]

developers.edit:
  path: /{developer}
  controller: App\Controller\DeveloperController::edit
  methods: [PUT]

developers.delete:
  path: /{developer}
  controller: App\Controller\DeveloperController::delete
  methods: [DELETE]
