developers.index:
  path: /
  controller: App\Action\Developer\Index
  methods: [GET]

developers.create:
  path: /
  controller: App\Action\Developer\Create
  methods: [POST]

developers.show:
  path: /{developer}
  controller: App\Action\Developer\Show
  methods: [GET]

developers.edit:
  path: /{developer}
  controller: App\Action\Developer\Edit
  methods: [PUT]

developers.delete:
  path: /{developer}
  controller: App\Action\Developer\Delete
  methods: [DELETE]
