posts.index:
  path: /
  controller: App\Action\Post\Index
  methods: [GET]

posts.show:
  path: /{post}
  controller: App\Action\Post\Show
  methods: [GET]

posts.create:
  path: /
  controller: App\Action\Post\Create
  methods: [POST]

posts.comments:
  path: /{post}/comments
  controller: App\Action\Comment\ByPost
  methods: [GET]

posts.comments.create:
  path: /{post}/comments
  controller: App\Action\Comment\Create
  methods: [POST]

posts.likes.list:
  path: /{post}/likes
  controller: App\Action\Like\ByPost
  methods: [GET]

posts.likes.create:
  path: /{post}/likes
  controller: App\Action\Like\Create
  methods: [POST]

posts.likes.delete:
  path: /{post}/likes/{developer}
  controller: App\Action\Like\Delete
  methods: [DELETE]

posts.edit:
  path: /{post}
  controller: App\Action\Post\Edit
  methods: [PUT]

posts.delete:
  path: /{post}
  controller: App\Action\Post\Delete
  methods: [DELETE]
