posts.index:
  path: /
  controller: App\Action\Post\Index
  methods: [GET]

posts.show:
  path: /{post}
  controller: App\Action\Post\Show
  methods: [GET]

posts.create:
  path: /
  controller: App\Action\Post\Create
  methods: [POST]

posts.comments:
  path: /{post}/comments
  controller: App\Action\Post\Comments\Index
  methods: [GET]

posts.comments.create:
  path: /{post}/comments
  controller: App\Action\Post\Comments\Create
  methods: [POST]

posts.likes.list:
  path: /{post}/likes
  controller: App\Action\Post\Likes\Index
  methods: [GET]

posts.likes.create:
  path: /{post}/likes
  controller: App\Action\Post\Likes\Create
  methods: [POST]

posts.likes.delete:
  path: /{post}/likes/{developer}
  controller: App\Action\Post\Likes\Delete
  methods: [DELETE]

posts.trends.list:
  path: /{post}/trends
  controller: App\Action\Post\Trends\Index
  methods: [GET]

posts.edit:
  path: /{post}
  controller: App\Action\Post\Edit
  methods: [PUT]

posts.delete:
  path: /{post}
  controller: App\Action\Post\Delete
  methods: [DELETE]
