trends.index:
  path: /
  controller: App\Action\Trend\Index
  methods: [GET]
  defaults:
    offset: ~
    limit: ~

trends.create:
  path: /
  controller: App\Action\Trend\Create
  methods: [POST]

trends.show:
  path: /{trend}
  controller: App\Action\Trend\Show
  methods: [GET]

trends.edit:
  path: /{trend}
  controller: App\Action\Trend\Edit
  methods: [PUT]

trends.delete:
  path: /{trend}
  controller: App\Action\Trend\Delete
  methods: [DELETE]
