---
- name: Ensure vault secrets are set up locally
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - shared_vars/vault.yml
  tasks:
    - name: "get uid running the playbook"
      become: false
      local_action: command id -u
      register: host_uid

    - debug:
        var: host_uid.stdout

    - name: "get gid running the playbook"
      become: false
      local_action: command id -g
      register: host_gid

    - debug:
        var: host_gid.stdout

    - name: "Ensure ../../.dplanet-vault folder exists"
      file:
        state: directory
        path: "../../.dplanet-vault"
        owner: "{{ host_uid.stdout }}"
        group: "{{ host_gid.stdout }}"
        mode: '700'

    - name: "Ensure vault secrets are in secret folder"
      copy:
        dest: "../../.dplanet-vault/{{ item.key }}"
        content: "{{ item.value }}"
        owner: "{{ host_uid.stdout }}"
        group: "{{ host_gid.stdout }}"
        mode: '700'
      no_log: true
      loop: "{{ lookup('dict', docker_secrets) }}"
