posts.index:
  path: /
  controller: App\Controller\PostController::index
  methods: [GET]

posts.create:
  path: /new
  controller: App\Controller\PostController::create
  methods: [GET, POST]

posts.edit:
  path: /{post}/edit
  controller: App\Controller\PostController::edit
  methods: [GET, PATCH, PUT, POST]

posts.delete:
  path: /{post}/delete
  controller: App\Controller\PostController::delete
  methods: [DELETE]

posts.show:
  path: /{post}
  controller: App\Controller\PostController::show
  methods: [GET]
