App\Entity\Comment:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    body:
      type: text
      options:
        default: ''
    isDeleted:
      type: boolean
      options:
        default: false
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update

  manyToOne:
    postedBy:
      targetEntity: Developer
      mappedBy: comments
      inversedBy: comments
    postedTo:
      targetEntity: Post
      mappedBy: comments
      inversedBy: comments