App\Entity\FriendRequest:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    isDeleted:
      type: boolean
      options:
        default: false
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    sender:
      targetEntity: Developer
      mappedBy: sentFriendRequests
      inversedBy: sentFriendRequests
    receiver:
      targetEntity: Developer
      mappedBy: receivedFriendRequests
      inversedBy: receivedFriendRequests
