App\Entity\Image:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    isDeleted:
      type: boolean
      options:
        default: false
    mimeType:
      type: string
      options:
        default: ''
    filename:
      type: string
      options:
        default: ''
    filePath:
      type: string
      options:
        default: ''
    publicPath:
      type: string
      options:
        default: ''
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
