App\Entity\Like:
  type: entity
  table: app_likes
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    isDeleted:
      type: boolean
      options:
        default: false
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    developer:
      targetEntity: Developer
      mappedBy: likes
      inversedBy: likes
    post:
      targetEntity: Post
      mappedBy: likes
      inversedBy: likes
