App\Entity\Message:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    body:
      type: text
      options:
        default: ''
    isOpened:
      type: boolean
      options:
        default: false
    isDeleted:
      type: boolean
      options:
        default: false
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    sender:
      targetEntity: Developer
      mappedBy: sentMessages
      inversedBy: sentMessages
    receiver:
      targetEntity: Developer
      mappedBy: receivedMessages
      inversedBy: receivedMessages
